// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteNoteFile(arg1) {
  return window['go']['main']['App']['DeleteNoteFile'](arg1);
}

export function GetFiles() {
  return window['go']['main']['App']['GetFiles']();
}

export function GetSelectedNote() {
  return window['go']['main']['App']['GetSelectedNote']();
}

export function GoBack() {
  return window['go']['main']['App']['GoBack']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function IsNotesDir() {
  return window['go']['main']['App']['IsNotesDir']();
}

export function NewFolder(arg1) {
  return window['go']['main']['App']['NewFolder'](arg1);
}

export function NewNote(arg1) {
  return window['go']['main']['App']['NewNote'](arg1);
}

export function SaveFileContent(arg1, arg2) {
  return window['go']['main']['App']['SaveFileContent'](arg1, arg2);
}

export function SelectDir(arg1) {
  return window['go']['main']['App']['SelectDir'](arg1);
}

export function SelectNote(arg1) {
  return window['go']['main']['App']['SelectNote'](arg1);
}

export function SetTitle(arg1, arg2) {
  return window['go']['main']['App']['SetTitle'](arg1, arg2);
}
