// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {context} from '../models';

export function GetFiles():Promise<main.ReturnValue>;

export function Greet(arg1:string):Promise<string>;

export function SetTitle(arg1:context.Context,arg2:string):Promise<void>;
